_commit: v0.0.1-17-g365d66c
_src_path: https://github.com/jevangoh/q6taaj04do99vgf9cog0gurq6.git
minimum_python_version: "3.14"
orcid: 0009-0000-2958-6605
orcid_family_name: Goh
orcid_given_name: Kheng Xi Jevan
owner_email: javerngoh@gmail.com
owner_name: Jevan Goh
project_id: dt9ezskevixgm3q01tdb3z8ak
python_type: function
